### ISSUE TITLE
Error in import

### ISSUE THREAD

**Issue by mateuszilli** [vitaminjs/query-builder#27]
Import lib in typescript project is causing the following error:

![e](https://user-images.githubusercontent.com/36007412/67892036-a19f0280-fb32-11e9-9cc6-2bef78277d1e.png)

Can you help me?

**Comment by absolux** [comment]
@mateuszilli The error is due to the `length` helper, which is appended to the `factory` function, and causes an error because `length` property is read-only in functions.

A fix will be available soon :sweat_smile:
